### ISSUE TITLE
Textual Image while executing dalek executable

### ISSUE THREAD

**Issue by Thirunavukkarasu** [dalekjs/dalek-cli#14]
Hey! First of all, thanks for inventing this wonderful product! This is really awesome! Every time i execute the dalek with my test script I'm getting the textual Image something like below. And this only happening after the re-installation.

[thiru@localhost]$dalek Deployed_code.js
       _____|_
      /       \
       <=====>
  Æ----<=====>
       =======
      c o o o Æ
     c o  o  o Æ
    c  o  o  o  Æ
    c__o__o__o__Æ
    [___________]

Thanks!

**Comment by asciidisco** [comment]
I thin you installed the wrong package. You need to install the `dalek-cli` package gloablly & the `dalekjs` dependency locally. You probably installed the `dalek` package, which has nothing to do with DalekJS - https://www.npmjs.com/package/dalek
